<?php

declare(strict_types=1);

namespace Dump\DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20210404010450 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE cart (id VARCHAR(255) NOT NULL, user_id BIGINT DEFAULT NULL, reference VARCHAR(255) DEFAULT NULL, content LONGTEXT DEFAULT NULL, UNIQUE INDEX UNIQ_BA388B7A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE chat (id VARCHAR(255) NOT NULL, room VARCHAR(255) NOT NULL, initiator BIGINT NOT NULL, participant BIGINT NOT NULL, order_id BIGINT NOT NULL, type VARCHAR(100) DEFAULT NULL, status VARCHAR(100) DEFAULT NULL, created_at DATETIME DEFAULT NULL, INDEX chat_room_idx (room), INDEX chat_initiator_idx (initiator), INDEX chat_participant_idx (participant), INDEX chat_order_id_idx (order_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE chat_message (id VARCHAR(255) NOT NULL, room VARCHAR(255) NOT NULL, sender BIGINT NOT NULL, sender_read TINYINT(1) NOT NULL, recipient BIGINT NOT NULL, recipient_read TINYINT(1) NOT NULL, message LONGTEXT DEFAULT NULL, deleted LONGTEXT DEFAULT NULL, created_at DATETIME DEFAULT NULL, INDEX chat_room_idx (room), INDEX chat_sender_idx (sender), INDEX chat_recipient_idx (recipient), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mail_queue (id VARCHAR(255) NOT NULL, connection VARCHAR(255) DEFAULT \'default\' NOT NULL, batch VARCHAR(255) DEFAULT NULL, entity_id BIGINT DEFAULT 0 NOT NULL, entity_name VARCHAR(255) DEFAULT NULL, payload LONGTEXT DEFAULT NULL, success INT DEFAULT 0 NOT NULL, failed INT DEFAULT 0 NOT NULL, created_at DATETIME DEFAULT NULL, INDEX mail_queue_connection_idx (connection), INDEX mail_queue_batch_idx (batch), INDEX mail_queue_entity_id_idx (entity_id), INDEX mail_queue_entity_name_idx (entity_name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE newsletter (id BIGINT AUTO_INCREMENT NOT NULL, email VARCHAR(100) NOT NULL, created_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_7E8585C8E7927C74 (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE notification (id BIGINT AUTO_INCREMENT NOT NULL, buyer_id BIGINT DEFAULT 0 NOT NULL, seller_id BIGINT DEFAULT 0 NOT NULL, title VARCHAR(255) DEFAULT NULL, content VARCHAR(255) DEFAULT NULL, is_sent_to_buyer TINYINT(1) NOT NULL, is_sent_to_seller TINYINT(1) NOT NULL, is_admin TINYINT(1) DEFAULT \'0\' NOT NULL, url VARCHAR(255) DEFAULT NULL, read_at DATETIME DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX notification_buyer_id_idx (buyer_id), INDEX notification_seller_id_idx (seller_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `order` (id BIGINT AUTO_INCREMENT NOT NULL, store_id BIGINT DEFAULT NULL, user_id BIGINT DEFAULT NULL, invoice VARCHAR(100) NOT NULL, shared_id VARCHAR(255) DEFAULT NULL, shared_invoice VARCHAR(255) DEFAULT NULL, total NUMERIC(15, 2) NOT NULL, status VARCHAR(50) DEFAULT \'pending\' NOT NULL, note LONGTEXT DEFAULT NULL, shipping_courier VARCHAR(255) DEFAULT NULL, shipping_service VARCHAR(255) DEFAULT NULL, shipping_price NUMERIC(15, 2) NOT NULL, tracking_code VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, tax_document_email VARCHAR(255) DEFAULT NULL, tax_document_phone VARCHAR(255) DEFAULT NULL, tax_document_file VARCHAR(255) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, address_url VARCHAR(255) DEFAULT NULL, address_map VARCHAR(255) DEFAULT NULL, address_lat NUMERIC(10, 8) DEFAULT NULL, address_lng NUMERIC(11, 8) DEFAULT NULL, map_place_id LONGTEXT DEFAULT NULL, post_code VARCHAR(10) DEFAULT NULL, city VARCHAR(100) DEFAULT NULL, city_id BIGINT DEFAULT 0 NOT NULL, district VARCHAR(100) DEFAULT NULL, district_id BIGINT DEFAULT 0 NOT NULL, province VARCHAR(100) DEFAULT NULL, province_id BIGINT DEFAULT 0 NOT NULL, country VARCHAR(100) DEFAULT NULL, country_id BIGINT DEFAULT 0 NOT NULL, is_b2g_transaction TINYINT(1) DEFAULT \'0\' NOT NULL, bast_file VARCHAR(255) DEFAULT NULL, delivery_paper_file VARCHAR(255) DEFAULT NULL, tax_invoice_file VARCHAR(255) DEFAULT NULL, invoice_file VARCHAR(255) DEFAULT NULL, chat_room_id VARCHAR(255) DEFAULT NULL, negotiation_status VARCHAR(255) DEFAULT \'none\' NOT NULL, execution_time VARCHAR(255) DEFAULT NULL, job_package_name VARCHAR(255) DEFAULT NULL, fiscal_year VARCHAR(255) DEFAULT NULL, source_of_fund VARCHAR(255) DEFAULT NULL, budget_ceiling VARCHAR(255) DEFAULT NULL, receipt_file VARCHAR(255) DEFAULT NULL, work_order_letter_file VARCHAR(255) DEFAULT NULL, qris_bill_number VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_F529939890651744 (invoice), INDEX IDX_F5299398B092A811 (store_id), INDEX IDX_F5299398A76ED395 (user_id), INDEX order_shared_id_idx (shared_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE order_complaint (id BIGINT AUTO_INCREMENT NOT NULL, order_id BIGINT DEFAULT NULL, description LONGTEXT DEFAULT NULL, is_resolved TINYINT(1) NOT NULL, resolved_at DATETIME DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_E3A0494D8D9F6D38 (order_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE order_negotiation (id BIGINT AUTO_INCREMENT NOT NULL, order_id BIGINT DEFAULT NULL, product_id BIGINT DEFAULT 0 NOT NULL, submitted_by BIGINT DEFAULT 0 NOT NULL, submitted_as VARCHAR(255) DEFAULT NULL, negotiated_price NUMERIC(15, 2) NOT NULL, execution_time VARCHAR(255) DEFAULT NULL, is_approved TINYINT(1) DEFAULT \'0\' NOT NULL, merchant_approval TINYINT(1) DEFAULT \'0\' NOT NULL, customer_approval TINYINT(1) DEFAULT \'0\' NOT NULL, batch INT DEFAULT 0 NOT NULL, note LONGTEXT DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_C2AEA1E8D9F6D38 (order_id), INDEX order_negotiation_product_id_idx (product_id), INDEX order_negotiation_submitted_by_idx (submitted_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE order_payment (id BIGINT AUTO_INCREMENT NOT NULL, order_id BIGINT DEFAULT NULL, invoice VARCHAR(100) NOT NULL, name VARCHAR(200) NOT NULL, email VARCHAR(100) NOT NULL, type VARCHAR(100) NOT NULL, date DATE NOT NULL, attachment VARCHAR(255) NOT NULL, nominal NUMERIC(15, 2) NOT NULL, message LONGTEXT DEFAULT NULL, bank_name VARCHAR(200) DEFAULT NULL, bank_account_name VARCHAR(200) DEFAULT NULL, bank_account_number VARCHAR(200) DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_9B522D468D9F6D38 (order_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE order_product (id VARCHAR(255) NOT NULL, order_id BIGINT DEFAULT NULL, product_id BIGINT DEFAULT NULL, quantity BIGINT DEFAULT 0 NOT NULL, price NUMERIC(15, 2) NOT NULL, base_price NUMERIC(15, 2) NOT NULL, price_before_negotiation NUMERIC(15, 2) DEFAULT \'0.00\' NOT NULL, total_price NUMERIC(15, 2) NOT NULL, note LONGTEXT DEFAULT NULL, with_tax TINYINT(1) NOT NULL, tax_value VARCHAR(255) DEFAULT NULL, tax_nominal NUMERIC(15, 2) NOT NULL, original_id BIGINT DEFAULT 0, original_name VARCHAR(255) DEFAULT NULL, INDEX IDX_2530ADE68D9F6D38 (order_id), INDEX IDX_2530ADE64584665A (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product (id BIGINT AUTO_INCREMENT NOT NULL, store_id BIGINT DEFAULT NULL, name VARCHAR(200) NOT NULL, slug VARCHAR(200) NOT NULL, category VARCHAR(255) DEFAULT NULL, keywords VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, note LONGTEXT DEFAULT NULL, quantity INT NOT NULL, price NUMERIC(15, 2) NOT NULL, base_price NUMERIC(15, 2) NOT NULL, status VARCHAR(20) DEFAULT \'draft\' NOT NULL, unit VARCHAR(20) DEFAULT \'unit\' NOT NULL, weight VARCHAR(255) DEFAULT NULL, dir_slug VARCHAR(100) DEFAULT NULL, featured TINYINT(1) NOT NULL, view_count BIGINT NOT NULL, rating_count BIGINT NOT NULL, review_total BIGINT NOT NULL, previous_values LONGTEXT DEFAULT NULL, previous_changes LONGTEXT DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_D34A04AD989D9B62 (slug), INDEX IDX_D34A04ADB092A811 (store_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_category (id BIGINT AUTO_INCREMENT NOT NULL, parent_id BIGINT DEFAULT 0 NOT NULL, name VARCHAR(200) NOT NULL, slug VARCHAR(200) NOT NULL, heading VARCHAR(200) DEFAULT NULL, description LONGTEXT DEFAULT NULL, desktop_image VARCHAR(255) DEFAULT NULL, mobile_image VARCHAR(255) DEFAULT NULL, status TINYINT(1) NOT NULL, featured TINYINT(1) NOT NULL, sort INT NOT NULL, dir_slug VARCHAR(100) DEFAULT NULL, with_tax TINYINT(1) DEFAULT \'0\' NOT NULL, class_name VARCHAR(100) DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_CDFC7356989D9B62 (slug), INDEX product_category_parent_id_idx (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_file (id BIGINT AUTO_INCREMENT NOT NULL, product_id BIGINT DEFAULT NULL, file_name VARCHAR(100) NOT NULL, file_type VARCHAR(20) DEFAULT \'image\' NOT NULL, file_mime_type VARCHAR(20) NOT NULL, file_path VARCHAR(200) NOT NULL, file_status VARCHAR(20) DEFAULT \'draft\' NOT NULL, is_default TINYINT(1) NOT NULL, sort INT NOT NULL, created_at DATETIME DEFAULT NULL, INDEX IDX_17714B14584665A (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_review (id BIGINT AUTO_INCREMENT NOT NULL, order_id BIGINT DEFAULT NULL, product_id BIGINT DEFAULT NULL, user_id BIGINT DEFAULT NULL, review LONGTEXT DEFAULT NULL, rating SMALLINT DEFAULT 0 NOT NULL, status VARCHAR(20) DEFAULT \'draft\' NOT NULL, attachment VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_1B3FC0628D9F6D38 (order_id), INDEX IDX_1B3FC0624584665A (product_id), INDEX IDX_1B3FC062A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE qris (id BIGINT AUTO_INCREMENT NOT NULL, invoice VARCHAR(255) DEFAULT NULL, bill_number VARCHAR(255) DEFAULT NULL, record_id BIGINT DEFAULT 0 NOT NULL, trx_id BIGINT DEFAULT 0 NOT NULL, trx_date VARCHAR(255) DEFAULT NULL, trx_status VARCHAR(255) DEFAULT NULL, trx_status_detail LONGTEXT DEFAULT NULL, reference_number VARCHAR(255) DEFAULT NULL, amount NUMERIC(15, 2) DEFAULT \'0.00\' NOT NULL, tips NUMERIC(15, 2) DEFAULT \'0.00\' NOT NULL, total_amount NUMERIC(15, 2) DEFAULT \'0.00\' NOT NULL, qr_id BIGINT DEFAULT 0 NOT NULL, qr_value LONGTEXT DEFAULT NULL, qr_image LONGTEXT DEFAULT NULL, qr_status VARCHAR(255) DEFAULT NULL, nmid VARCHAR(255) DEFAULT NULL, mid VARCHAR(255) DEFAULT NULL, merchant_name VARCHAR(255) DEFAULT NULL, product_code VARCHAR(255) DEFAULT NULL, issuer_name VARCHAR(255) DEFAULT NULL, response_code VARCHAR(255) DEFAULT NULL, mdr_percentage VARCHAR(255) DEFAULT NULL, net_nominal VARCHAR(255) DEFAULT NULL, branch_code VARCHAR(255) DEFAULT NULL, refund_date VARCHAR(255) DEFAULT NULL, created_date VARCHAR(255) DEFAULT NULL, expired_date VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX qris_invoice_idx (invoice), INDEX qris_bill_number_idx (bill_number), INDEX qris_trx_id_idx (trx_id), INDEX qris_trx_status_idx (trx_status), INDEX qris_reference_number_idx (reference_number), INDEX qris_qr_id_idx (qr_id), INDEX qris_qr_status_idx (qr_status), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE setting (id BIGINT AUTO_INCREMENT NOT NULL, slug VARCHAR(30) NOT NULL, name VARCHAR(100) NOT NULL, description LONGTEXT DEFAULT NULL, type VARCHAR(30) NOT NULL, default_value LONGTEXT DEFAULT NULL, options LONGTEXT DEFAULT NULL, namespace VARCHAR(50) DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_9F74B898989D9B62 (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE store (id BIGINT AUTO_INCREMENT NOT NULL, user_id BIGINT DEFAULT NULL, name VARCHAR(200) NOT NULL, slug VARCHAR(200) NOT NULL, color VARCHAR(255) DEFAULT NULL, theme VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, is_active TINYINT(1) NOT NULL, is_verified TINYINT(1) NOT NULL, is_pkp TINYINT(1) DEFAULT \'0\' NOT NULL, delivery_couriers LONGTEXT DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, address_url VARCHAR(255) DEFAULT NULL, address_map VARCHAR(255) DEFAULT NULL, address_lat NUMERIC(10, 8) DEFAULT NULL, address_lng NUMERIC(11, 8) DEFAULT NULL, map_place_id LONGTEXT DEFAULT NULL, post_code VARCHAR(10) DEFAULT NULL, city VARCHAR(100) DEFAULT NULL, city_id BIGINT DEFAULT 0 NOT NULL, district VARCHAR(100) DEFAULT NULL, district_id BIGINT DEFAULT 0 NOT NULL, province VARCHAR(100) DEFAULT NULL, province_id BIGINT DEFAULT 0 NOT NULL, country VARCHAR(100) DEFAULT NULL, country_id BIGINT DEFAULT 0 NOT NULL, previous_values LONGTEXT DEFAULT NULL, previous_changes LONGTEXT DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_FF575877989D9B62 (slug), INDEX IDX_FF575877A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE store_owner_log (id BIGINT AUTO_INCREMENT NOT NULL, store_id BIGINT DEFAULT 0 NOT NULL, current_owner BIGINT DEFAULT 0 NOT NULL, previous_owner BIGINT DEFAULT 0 NOT NULL, updated_by BIGINT DEFAULT 0 NOT NULL, reason LONGTEXT DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX store_owner_log_store_id_idx (store_id), INDEX store_owner_log_current_owner_idx (current_owner), INDEX store_owner_log_previous_owner_idx (previous_owner), INDEX store_owner_log_updated_by_idx (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user (id BIGINT AUTO_INCREMENT NOT NULL, username VARCHAR(100) NOT NULL, email VARCHAR(100) NOT NULL, email_canonical VARCHAR(100) NOT NULL, password VARCHAR(255) NOT NULL, dir_slug VARCHAR(100) DEFAULT NULL, role VARCHAR(100) DEFAULT NULL, activation_code VARCHAR(255) DEFAULT NULL, forgot_password_code VARCHAR(255) DEFAULT NULL, is_active TINYINT(1) NOT NULL, is_deleted TINYINT(1) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) DEFAULT NULL, description LONGTEXT DEFAULT NULL, phone_number VARCHAR(20) DEFAULT NULL, gender VARCHAR(20) DEFAULT NULL, photo_profile VARCHAR(255) DEFAULT NULL, banner_profile VARCHAR(255) DEFAULT NULL, newsletter TINYINT(1) NOT NULL, dob DATE DEFAULT NULL, ip_address VARCHAR(20) DEFAULT NULL, nip VARCHAR(255) DEFAULT NULL, pp_name VARCHAR(255) DEFAULT NULL, ppk_name VARCHAR(255) DEFAULT NULL, nik VARCHAR(255) DEFAULT NULL, company_phone VARCHAR(255) DEFAULT NULL, company_role VARCHAR(255) DEFAULT NULL, npwp VARCHAR(255) DEFAULT NULL, npwp_file VARCHAR(255) DEFAULT NULL, lkpp_lpse_id VARCHAR(255) DEFAULT NULL, lkpp_employee_id VARCHAR(255) DEFAULT NULL, lkpp_groups VARCHAR(255) DEFAULT NULL, lkpp_kldi VARCHAR(255) DEFAULT NULL, lkpp_work_unit VARCHAR(255) DEFAULT NULL, lkpp_token VARCHAR(255) DEFAULT NULL, lkpp_token_expiration DATETIME DEFAULT NULL, lkpp_login_status VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_8D93D649F85E0677 (username), UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_address (id BIGINT AUTO_INCREMENT NOT NULL, user_id BIGINT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, address_url VARCHAR(255) DEFAULT NULL, address_map VARCHAR(255) DEFAULT NULL, address_lat NUMERIC(10, 8) DEFAULT NULL, address_lng NUMERIC(11, 8) DEFAULT NULL, map_place_id LONGTEXT DEFAULT NULL, post_code VARCHAR(10) DEFAULT NULL, city VARCHAR(100) DEFAULT NULL, city_id BIGINT DEFAULT 0 NOT NULL, district VARCHAR(100) DEFAULT NULL, district_id BIGINT DEFAULT 0 NOT NULL, province VARCHAR(100) DEFAULT NULL, province_id BIGINT DEFAULT 0 NOT NULL, country VARCHAR(100) DEFAULT NULL, country_id BIGINT DEFAULT 0 NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_5543718BA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_tax_document (id BIGINT AUTO_INCREMENT NOT NULL, user_id BIGINT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, number VARCHAR(255) DEFAULT NULL, email VARCHAR(100) DEFAULT NULL, phone VARCHAR(20) DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, same_as_profile TINYINT(1) NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_B83157CAA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE virtual_account (id BIGINT AUTO_INCREMENT NOT NULL, invoice VARCHAR(255) DEFAULT NULL, record_id VARCHAR(255) DEFAULT NULL, bill_number VARCHAR(255) DEFAULT NULL, transaction_id VARCHAR(255) DEFAULT NULL, reference_id VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, amount NUMERIC(15, 2) DEFAULT \'0.00\' NOT NULL, status VARCHAR(255) DEFAULT NULL, institution VARCHAR(255) DEFAULT NULL, paid_date VARCHAR(255) DEFAULT NULL, paid_status VARCHAR(255) DEFAULT NULL, kd_user VARCHAR(255) DEFAULT NULL, response LONGTEXT DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX virtual_account_invoice_idx (invoice), INDEX virtual_account_record_id_idx (record_id), INDEX virtual_account_bill_number_idx (bill_number), INDEX virtual_account_transaction_id_idx (transaction_id), INDEX virtual_account_reference_id_idx (reference_id), INDEX virtual_account_status_idx (status), INDEX virtual_account_paid_status_idx (paid_status), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE voucher (id BIGINT AUTO_INCREMENT NOT NULL, code VARCHAR(255) NOT NULL, name VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, base_type VARCHAR(255) DEFAULT \'coupon\', percentage BIGINT DEFAULT 0 NOT NULL, amount NUMERIC(15, 2) NOT NULL, start_at DATETIME DEFAULT NULL, end_at DATETIME DEFAULT NULL, usage_limit BIGINT DEFAULT 0 NOT NULL, usage_per_user BIGINT DEFAULT 0 NOT NULL, status VARCHAR(20) DEFAULT \'draft\' NOT NULL, qr_image VARCHAR(255) DEFAULT NULL, valid_for LONGTEXT DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX voucher_code_idx (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE voucher_used_log (id BIGINT AUTO_INCREMENT NOT NULL, voucher_id BIGINT DEFAULT 0 NOT NULL, user_id BIGINT DEFAULT 0 NOT NULL, order_id BIGINT DEFAULT 0 NOT NULL, order_shared_id VARCHAR(255) DEFAULT NULL, voucher_amount NUMERIC(15, 2) NOT NULL, order_amount NUMERIC(15, 2) NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX voucher_used_log_voucher_id_idx (voucher_id), INDEX voucher_used_log_user_id_idx (user_id), INDEX voucher_used_log_order_id_idx (order_id), INDEX voucher_used_log_order_shared_id_idx (order_shared_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE cart ADD CONSTRAINT FK_BA388B7A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE `order` ADD CONSTRAINT FK_F5299398B092A811 FOREIGN KEY (store_id) REFERENCES store (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE `order` ADD CONSTRAINT FK_F5299398A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE order_complaint ADD CONSTRAINT FK_E3A0494D8D9F6D38 FOREIGN KEY (order_id) REFERENCES `order` (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE order_negotiation ADD CONSTRAINT FK_C2AEA1E8D9F6D38 FOREIGN KEY (order_id) REFERENCES `order` (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE order_payment ADD CONSTRAINT FK_9B522D468D9F6D38 FOREIGN KEY (order_id) REFERENCES `order` (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE order_product ADD CONSTRAINT FK_2530ADE68D9F6D38 FOREIGN KEY (order_id) REFERENCES `order` (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE order_product ADD CONSTRAINT FK_2530ADE64584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04ADB092A811 FOREIGN KEY (store_id) REFERENCES store (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE product_file ADD CONSTRAINT FK_17714B14584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE product_review ADD CONSTRAINT FK_1B3FC0628D9F6D38 FOREIGN KEY (order_id) REFERENCES `order` (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE product_review ADD CONSTRAINT FK_1B3FC0624584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE product_review ADD CONSTRAINT FK_1B3FC062A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE store ADD CONSTRAINT FK_FF575877A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE user_address ADD CONSTRAINT FK_5543718BA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE user_tax_document ADD CONSTRAINT FK_B83157CAA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE SET NULL');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE order_complaint DROP FOREIGN KEY FK_E3A0494D8D9F6D38');
        $this->addSql('ALTER TABLE order_negotiation DROP FOREIGN KEY FK_C2AEA1E8D9F6D38');
        $this->addSql('ALTER TABLE order_payment DROP FOREIGN KEY FK_9B522D468D9F6D38');
        $this->addSql('ALTER TABLE order_product DROP FOREIGN KEY FK_2530ADE68D9F6D38');
        $this->addSql('ALTER TABLE product_review DROP FOREIGN KEY FK_1B3FC0628D9F6D38');
        $this->addSql('ALTER TABLE order_product DROP FOREIGN KEY FK_2530ADE64584665A');
        $this->addSql('ALTER TABLE product_file DROP FOREIGN KEY FK_17714B14584665A');
        $this->addSql('ALTER TABLE product_review DROP FOREIGN KEY FK_1B3FC0624584665A');
        $this->addSql('ALTER TABLE `order` DROP FOREIGN KEY FK_F5299398B092A811');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04ADB092A811');
        $this->addSql('ALTER TABLE cart DROP FOREIGN KEY FK_BA388B7A76ED395');
        $this->addSql('ALTER TABLE `order` DROP FOREIGN KEY FK_F5299398A76ED395');
        $this->addSql('ALTER TABLE product_review DROP FOREIGN KEY FK_1B3FC062A76ED395');
        $this->addSql('ALTER TABLE store DROP FOREIGN KEY FK_FF575877A76ED395');
        $this->addSql('ALTER TABLE user_address DROP FOREIGN KEY FK_5543718BA76ED395');
        $this->addSql('ALTER TABLE user_tax_document DROP FOREIGN KEY FK_B83157CAA76ED395');
        $this->addSql('DROP TABLE cart');
        $this->addSql('DROP TABLE chat');
        $this->addSql('DROP TABLE chat_message');
        $this->addSql('DROP TABLE mail_queue');
        $this->addSql('DROP TABLE newsletter');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE `order`');
        $this->addSql('DROP TABLE order_complaint');
        $this->addSql('DROP TABLE order_negotiation');
        $this->addSql('DROP TABLE order_payment');
        $this->addSql('DROP TABLE order_product');
        $this->addSql('DROP TABLE product');
        $this->addSql('DROP TABLE product_category');
        $this->addSql('DROP TABLE product_file');
        $this->addSql('DROP TABLE product_review');
        $this->addSql('DROP TABLE qris');
        $this->addSql('DROP TABLE setting');
        $this->addSql('DROP TABLE store');
        $this->addSql('DROP TABLE store_owner_log');
        $this->addSql('DROP TABLE user');
        $this->addSql('DROP TABLE user_address');
        $this->addSql('DROP TABLE user_tax_document');
        $this->addSql('DROP TABLE virtual_account');
        $this->addSql('DROP TABLE voucher');
        $this->addSql('DROP TABLE voucher_used_log');
    }
}
